import './styles/global.scss'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface IRootLayout {
  children: React.ReactNode;
}

const RootLayout: React.FC<IRootLayout> = ({ children }) => {
  return (
    <html lang="pt-br">
      <body>{children}</body>
    </html>
  );
};

export default RootLayout
