import "./styles/global.scss";

import { GothamFont } from "./fonts/Gotham";

export const metadata = {
  title: "Gianlucca Claudino | ",
  description: "Generated by create next app",
};

interface IRootLayout {
  children: React.ReactNode;
}

const RootLayout: React.FC<IRootLayout> = ({ children }) => {
  return (
    <html lang="pt-br">
      <body className={GothamFont.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
